

###
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "name":"Indrajeet Bhujbal",
  "email":"vu4f2324001@pvppcoe.ac.in",
  "password":"eedesdssdede",
  "role":"doctor"
}
###
###
POST   http://localhost:3000/api/v1/auth/signin
Content-Type: application/json

{
 "email":"ajit@gmail.com",
 "password":"ancdkjkfded"
}
###


POST http://localhost:3000/api/v1/auth/verify-otp
Content-Type: application/json

{
  "userId": 12,
  "token": "935682"
}
###

POST http://localhost:3000/api/v1/doctors/1
Content-Type: application/json

{
  "mobileNo":"1234567890",
  "fees":"300",
  "speciality":"ginacologist",
  "location":"mumbai",
  "experience":"4 years",
  "degree":"MBBS",
  "gender":"Male",
  "available":true
}
###

GET http://localhost:3000/api/v1/doctors/ginacologist

###  create doc availability

POST http://localhost:3000/api/v1/availability/1
Content-Type: application/json

{
  "weekdays":["Monday","Tuesday","Wednesday","Thursday","Friday"],
  "sessions":["MORNING"],
  "startTime":"09:00",
  "endTime":"12:00",
  "capacity":3,
  "slotCreation":"automatic",
  "scheduleType": "WAVE",
  "slotPeriod":"30"
  
}
###


POST http://localhost:3000/api/v1/patients/2
Content-Type: application/json

{
  "phone": "1234567890",
  "dob": "2005-10-10",
  "age": 34,
  "gender": "Male",
  "medicalHistory":"had a heart surgury"
}
###

###
POST http://localhost:3000/api/v1/slots/automatic/1
Content-Type: application/json 

{
  "capacity":3,
  "slotPeriod":30,
  "startTime":"09.00",
  "endTime":"12.00"
}

###
POST http://localhost:3000/api/v1/slots/manual/7
Content-Type: application/json


{
 "slots":[
  {"timing":"09:00-12.00","capacity":10}
 ]
}
###

POST  http://localhost:3000/api/v1/appointments/1/1/10
Content-Type: application/json

{
  "scheduledOn":"2025-10-10",
  "slot":"09:30-10:00",
  "message":"stomach pain"
}

###